services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - name: postgres
        target: 5432
        published: 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petstore
